// ------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated.
//
//     - To turn off auto-generation set:
//
//         [TeamCity (AutoGenerate = false)]
//
//     - To trigger manual generation invoke:
//
//         nuke --configure-build-server --host TeamCity
//
// </auto-generated>
// ------------------------------------------------------------------------------

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.*
import jetbrains.buildServer.configs.kotlin.v2018_1.triggers.*
import jetbrains.buildServer.configs.kotlin.v2018_1.vcs.*

version = "2019.1"

project {
    vcsRoot(VcsRoot)

    buildType(Compile)
    buildType(Pack)
    buildType(Test_P1T2)
    buildType(Test_P2T2)
    buildType(Test)
    buildType(Coverage)
    buildType(Publish)
    buildType(Announce)

    buildTypesOrder = arrayListOf(Compile, Pack, Test_P1T2, Test_P2T2, Test, Coverage, Publish, Announce)

    params {
        select (
            "env.Verbosity",
            label = "Verbosity",
            description = "Logging verbosity during build execution. Default is 'Normal'.",
            value = "Normal",
            options = listOf("Minimal" to "Minimal", "Normal" to "Normal", "Quiet" to "Quiet", "Verbose" to "Verbose"),
            display = ParameterDisplay.NORMAL)
        select (
            "env.Configuration",
            label = "Configuration",
            description = "Configuration to build - Default is 'Debug' (local) or 'Release' (server)",
            value = "Release",
            options = listOf("Debug" to "Debug", "Release" to "Release"),
            display = ParameterDisplay.NORMAL)
        checkbox (
            "env.IgnoreFailedSources",
            label = "IgnoreFailedSources",
            value = "False",
            checked = "True",
            unchecked = "False",
            display = ParameterDisplay.NORMAL)
        text (
            "env.Source",
            label = "Source",
            description = "NuGet Source for Packages",
            value = "https://api.nuget.org/v3/index.json",
            allowEmpty = true,
            display = ParameterDisplay.NORMAL)
        text (
            "env.GitHubToken",
            label = "GitHubToken",
            description = "GitHub Token",
            value = "",
            allowEmpty = true,
            display = ParameterDisplay.NORMAL)
        checkbox (
            "env.AutoStash",
            label = "AutoStash",
            value = "True",
            checked = "True",
            unchecked = "False",
            display = ParameterDisplay.NORMAL)
        checkbox (
            "env.UseSSH",
            label = "UseSSH",
            value = "False",
            checked = "True",
            unchecked = "False",
            display = ParameterDisplay.NORMAL)
        param(
            "teamcity.runner.commandline.stdstreams.encoding",
            "IBM-437"
        )
    }
}
object VcsRoot : GitVcsRoot({
    name = "https://github.com/nuke-build/nuke.git#refs/heads/develop"
    url = "https://github.com/nuke-build/nuke.git"
    branch = "refs/heads/develop"
    pollInterval = 60
    branchSpec = """
        +:refs/heads/*
    """.trimIndent()
})
object Compile : BuildType({
    name = "⚙️ Compile"
    vcs {
        root(VcsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "Restore Compile --skip"
        }
    }
})
object Pack : BuildType({
    name = "📦 Pack"
    vcs {
        root(VcsRoot)
        cleanCheckout = true
    }
    artifactRules = """
        output/*.nupkg => output
    """.trimIndent()
    steps {
        exec {
            path = "build.cmd"
            arguments = "Pack --skip"
        }
    }
    triggers {
        vcs {
            branchFilter = ""
            triggerRules = "+:**"
        }
        schedule {
            schedulingPolicy = daily {
                hour = 3
            }
            branchFilter = ""
            triggerRules = "+:**"
            triggerBuild = always()
            withPendingChangesOnly = false
            enableQueueOptimization = true
            param("cronExpression_min", "3")
        }
    }
    dependencies {
        snapshot(Compile) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object Test_P1T2 : BuildType({
    name = "🚦 Test 🧩 1/2"
    vcs {
        root(VcsRoot)
        cleanCheckout = true
    }
    artifactRules = """
        output/*.trx => output
        output/*.xml => output
    """.trimIndent()
    steps {
        exec {
            path = "build.cmd"
            arguments = "Test --skip --test-partition 1"
        }
    }
    dependencies {
        snapshot(Compile) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object Test_P2T2 : BuildType({
    name = "🚦 Test 🧩 2/2"
    vcs {
        root(VcsRoot)
        cleanCheckout = true
    }
    artifactRules = """
        output/*.trx => output
        output/*.xml => output
    """.trimIndent()
    steps {
        exec {
            path = "build.cmd"
            arguments = "Test --skip --test-partition 2"
        }
    }
    dependencies {
        snapshot(Compile) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object Test : BuildType({
    name = "🚦 Test"
    type = Type.COMPOSITE
    vcs {
        root(VcsRoot)
        cleanCheckout = true
        showDependenciesChanges = true
    }
    artifactRules = """
        **/*
    """.trimIndent()
    triggers {
        vcs {
            branchFilter = ""
            triggerRules = "+:**"
        }
        schedule {
            schedulingPolicy = daily {
                hour = 3
            }
            branchFilter = ""
            triggerRules = "+:**"
            triggerBuild = always()
            withPendingChangesOnly = false
            enableQueueOptimization = true
            param("cronExpression_min", "3")
        }
    }
    dependencies {
        snapshot(Test_P1T2) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        snapshot(Test_P2T2) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        artifacts(Test_P1T2) {
            artifactRules = """
                **/*
            """.trimIndent()
        }
        artifacts(Test_P2T2) {
            artifactRules = """
                **/*
            """.trimIndent()
        }
    }
})
object Coverage : BuildType({
    name = "📊 Coverage"
    vcs {
        root(VcsRoot)
        cleanCheckout = true
    }
    artifactRules = """
        output/coverage-report.zip => output
    """.trimIndent()
    steps {
        exec {
            path = "build.cmd"
            arguments = "Coverage --skip"
        }
    }
    triggers {
        finishBuildTrigger {
            buildType = "${Test.id}"
        }
    }
    dependencies {
        snapshot(Test) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        artifacts(Test) {
            artifactRules = """
                output/*.trx => output
                output/*.xml => output
            """.trimIndent()
        }
    }
})
object Publish : BuildType({
    name = "🚚 Publish"
    type = Type.DEPLOYMENT
    vcs {
        root(VcsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "Publish --skip"
        }
    }
    params {
        text (
            "env.ApiKey",
            label = "ApiKey",
            description = "NuGet Api Key",
            value = "",
            allowEmpty = false,
            display = ParameterDisplay.PROMPT)
        text (
            "env.SlackWebhook",
            label = "SlackWebhook",
            description = "Slack Webhook",
            value = "",
            allowEmpty = false,
            display = ParameterDisplay.PROMPT)
        text (
            "env.GitterAuthToken",
            label = "GitterAuthToken",
            description = "Gitter Auth Token",
            value = "",
            allowEmpty = false,
            display = ParameterDisplay.PROMPT)
    }
    dependencies {
        snapshot(Test) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        snapshot(Pack) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        artifacts(Pack) {
            artifactRules = """
                output/*.nupkg => output
            """.trimIndent()
        }
    }
})
object Announce : BuildType({
    name = "🗣 Announce"
    vcs {
        root(VcsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "Announce --skip"
        }
    }
    triggers {
        finishBuildTrigger {
            buildType = "${Publish.id}"
        }
    }
})
