package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.ExecBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.exec
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Compile'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Compile")) {
    expectSteps {
        exec {
            path = "build.cmd"
            arguments = "Restore Compile --skip"
        }
    }
    steps {
        update<ExecBuildStep>(0) {
            clearConditions()
            path = "./build.cmd"
        }
    }
}
