package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("env.EnterpriseAccessToken", "", label = "EnterpriseAccessToken")
        }
        update {
            password("env.EnterpriseAccessToken", "credentialsJSON:02c23844-4f9a-49c2-95a6-320497f8abc3", label = "EnterpriseAccessToken")
        }
        expect {
            password("env.SlackUserAccessToken", "", label = "SlackUserAccessToken")
        }
        update {
            password("env.SlackUserAccessToken", "credentialsJSON:40784596-735c-4e57-98d4-5f8b1894fedb", label = "SlackUserAccessToken")
        }
    }
}
