//HintName: AccessInheritanceAsMembersGenerator.cs
// <auto-generated/>
using System;

internal partial class Build
{
    protected IDisposable IDisposable  => this;
    protected global::Nuke.Common.CI.IBuildServer IBuildServer  => this;
}
