//HintName: Solution.g.cs
// <auto-generated/>

using Microsoft.VisualStudio.SolutionPersistence.Model;
using Nuke.Common.ProjectModel;
using Nuke.Common.IO;

internal class Solution(SolutionModel model, AbsolutePath path) : Nuke.Common.ProjectModel.Solution(model, path)
{
    public Nuke.Common.ProjectModel.Project _build => this.GetProject("_build");
    public Nuke.Common.ProjectModel.Project Nuke_Build => this.GetProject("Nuke.Build");
    public Nuke.Common.ProjectModel.Project Nuke_Build_Shared => this.GetProject("Nuke.Build.Shared");
    public Nuke.Common.ProjectModel.Project Nuke_Build_Tests => this.GetProject("Nuke.Build.Tests");
    public Nuke.Common.ProjectModel.Project Nuke_Common => this.GetProject("Nuke.Common");
    public Nuke.Common.ProjectModel.Project Nuke_Common_Tests => this.GetProject("Nuke.Common.Tests");
    public Nuke.Common.ProjectModel.Project Nuke_Components => this.GetProject("Nuke.Components");
    public Nuke.Common.ProjectModel.Project Nuke_GlobalTool => this.GetProject("Nuke.GlobalTool");
    public Nuke.Common.ProjectModel.Project Nuke_GlobalTool_Tests => this.GetProject("Nuke.GlobalTool.Tests");
    public Nuke.Common.ProjectModel.Project Nuke_MSBuildTasks => this.GetProject("Nuke.MSBuildTasks");
    public Nuke.Common.ProjectModel.Project Nuke_ProjectModel => this.GetProject("Nuke.ProjectModel");
    public Nuke.Common.ProjectModel.Project Nuke_ProjectModel_Tests => this.GetProject("Nuke.ProjectModel.Tests");
    public Nuke.Common.ProjectModel.Project Nuke_SolutionModel => this.GetProject("Nuke.SolutionModel");
    public Nuke.Common.ProjectModel.Project Nuke_SolutionModel_Tests => this.GetProject("Nuke.SolutionModel.Tests");
    public Nuke.Common.ProjectModel.Project Nuke_SourceGenerators => this.GetProject("Nuke.SourceGenerators");
    public Nuke.Common.ProjectModel.Project Nuke_SourceGenerators_Tests => this.GetProject("Nuke.SourceGenerators.Tests");
    public Nuke.Common.ProjectModel.Project Nuke_Tooling => this.GetProject("Nuke.Tooling");
    public Nuke.Common.ProjectModel.Project Nuke_Tooling_Generator => this.GetProject("Nuke.Tooling.Generator");
    public Nuke.Common.ProjectModel.Project Nuke_Tooling_Tests => this.GetProject("Nuke.Tooling.Tests");
    public Nuke.Common.ProjectModel.Project Nuke_Utilities => this.GetProject("Nuke.Utilities");
    public Nuke.Common.ProjectModel.Project Nuke_Utilities_IO_Compression => this.GetProject("Nuke.Utilities.IO.Compression");
    public Nuke.Common.ProjectModel.Project Nuke_Utilities_IO_Globbing => this.GetProject("Nuke.Utilities.IO.Globbing");
    public Nuke.Common.ProjectModel.Project Nuke_Utilities_Net => this.GetProject("Nuke.Utilities.Net");
    public Nuke.Common.ProjectModel.Project Nuke_Utilities_Tests => this.GetProject("Nuke.Utilities.Tests");
    public Nuke.Common.ProjectModel.Project Nuke_Utilities_Text_Json => this.GetProject("Nuke.Utilities.Text.Json");
    public Nuke.Common.ProjectModel.Project Nuke_Utilities_Text_Yaml => this.GetProject("Nuke.Utilities.Text.Yaml");

    public _misc misc => new(this.GetSolutionFolder("misc").GetModel(), this);

    internal class _misc(SolutionFolderModel model, Nuke.Common.ProjectModel.Solution solution) : Nuke.Common.ProjectModel.SolutionFolder(model, solution)
    {
    
    
    }
}